name: Deploy to GKE

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          service_account_key: ${{ secrets.GKE_SA_KEY }}
          project_id: ${{ secrets.GKE_PROJECT }}

      - name: Authenticate with GKE
        run: |
          gcloud container clusters get-credentials ${{ secrets.GKE_CLUSTER }} \
            --zone ${{ secrets.GKE_ZONE }}

      - name: Deploy Resources
        run: |
          kubectl apply -f mysql-configMap.yaml --namespace=springboot-app-test
          kubectl apply -f mysql-secrets.yaml --namespace=springboot-app-test
          kubectl apply -f db-deployment.yaml --namespace=springboot-app-test
          kubectl apply -f app-deployment.yaml --namespace=springboot-app-test

      - name: Verify Deployment
        run: kubectl get pods --namespace=springboot-app-test
